# version: "3.8"  # Removed as it's obsolete

services:
  backend:
    build: ./backend
    container_name: backend-sp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test-super-market-05
      - TZ=Asia/Colombo
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/src/config/serviceAccountKey.json:/app/src/config/serviceAccountKey.json
    restart: on-failure

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-sp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-sp
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./frontend/admin_web/out:/usr/share/nginx/html:ro
    restart: always


volumes:
  mongodb_data: