version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-sp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test-super-market-05
      - TZ=Asia/Colombo
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/src/config/serviceAccountKey.json:/app/src/config/serviceAccountKey.json
    restart: on-failure

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-sp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-sp
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/webroot:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    entrypoint: ""
    command: >
      certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email groupathukorala@gmail.com
      --agree-tos
      --no-eff-email
      -d afmdelivery.lk

volumes:
  mongodb_data: