events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name afmdelivery.lk www.afmdelivery.lk;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 'Server is running';
            add_header Content-Type text/plain;
        }
    }
}
