export const DAYS = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']
export const ORDER_STATUS_ENUM = {
  INITIATED: 'INITIATED',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED'
};

export const NOTIFICATION_TYPES = {
  REVIEW_ORDER: 'REVIEW_ORDER'
}

export const FILTER_TYPE = {
  CHECKBOX: 'checkbox',
  RADIO: 'radio'
}
